package sys

import (
	"testing"
	"unsafe"
)

// Expected values measured with gcc against va.h, va_dec_hevc.h and
// va_enc_hevc.h (libva 2.22); they are identical on x86-64 and arm64.
func TestHEVCStructLayouts(t *testing.T) {
	var pic PictureHEVC
	var pp PictureParameterBufferHEVC
	var sp SliceParameterBufferHEVC
	var iq IQMatrixBufferHEVC
	var es EncSequenceParameterBufferHEVC
	var ep EncPictureParameterBufferHEVC
	var el EncSliceParameterBufferHEVC

	checks := []struct {
		name string
		got  uintptr
		want uintptr
	}{
		{"sizeof VAPictureHEVC", unsafe.Sizeof(pic), 28},
		{"VAPictureHEVC.pic_order_cnt", unsafe.Offsetof(pic.PicOrderCnt), 4},
		{"VAPictureHEVC.flags", unsafe.Offsetof(pic.Flags), 8},
		{"sizeof VAPictureParameterBufferHEVC", unsafe.Sizeof(pp), 604},
		{"VAPictureParameterBufferHEVC.ReferenceFrames", unsafe.Offsetof(pp.ReferenceFrames), 28},
		{"VAPictureParameterBufferHEVC.pic_width_in_luma_samples", unsafe.Offsetof(pp.PicWidthInLumaSamples), 448},
		{"VAPictureParameterBufferHEVC.pic_height_in_luma_samples", unsafe.Offsetof(pp.PicHeightInLumaSamples), 450},
		{"VAPictureParameterBufferHEVC.pic_fields", unsafe.Offsetof(pp.PicFields), 452},
		{"VAPictureParameterBufferHEVC.sps_max_dec_pic_buffering_minus1", unsafe.Offsetof(pp.SpsMaxDecPicBufferingMinus1), 456},
		{"VAPictureParameterBufferHEVC.bit_depth_luma_minus8", unsafe.Offsetof(pp.BitDepthLumaMinus8), 457},
		{"VAPictureParameterBufferHEVC.pcm_sample_bit_depth_luma_minus1", unsafe.Offsetof(pp.PcmSampleBitDepthLumaMinus1), 459},
		{"VAPictureParameterBufferHEVC.log2_min_luma_coding_block_size_minus3", unsafe.Offsetof(pp.Log2MinLumaCodingBlockSizeMinus3), 461},
		{"VAPictureParameterBufferHEVC.max_transform_hierarchy_depth_intra", unsafe.Offsetof(pp.MaxTransformHierarchyDepthIntra), 467},
		{"VAPictureParameterBufferHEVC.init_qp_minus26", unsafe.Offsetof(pp.InitQpMinus26), 469},
		{"VAPictureParameterBufferHEVC.diff_cu_qp_delta_depth", unsafe.Offsetof(pp.DiffCuQpDeltaDepth), 470},
		{"VAPictureParameterBufferHEVC.pps_cb_qp_offset", unsafe.Offsetof(pp.PpsCbQpOffset), 471},
		{"VAPictureParameterBufferHEVC.log2_parallel_merge_level_minus2", unsafe.Offsetof(pp.Log2ParallelMergeLevelMinus2), 473},
		{"VAPictureParameterBufferHEVC.num_tile_columns_minus1", unsafe.Offsetof(pp.NumTileColumnsMinus1), 474},
		{"VAPictureParameterBufferHEVC.num_tile_rows_minus1", unsafe.Offsetof(pp.NumTileRowsMinus1), 475},
		{"VAPictureParameterBufferHEVC.column_width_minus1", unsafe.Offsetof(pp.ColumnWidthMinus1), 476},
		{"VAPictureParameterBufferHEVC.row_height_minus1", unsafe.Offsetof(pp.RowHeightMinus1), 514},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields", unsafe.Offsetof(pp.SliceParsingFields), 556},
		{"VAPictureParameterBufferHEVC.log2_max_pic_order_cnt_lsb_minus4", unsafe.Offsetof(pp.Log2MaxPicOrderCntLsbMinus4), 560},
		{"VAPictureParameterBufferHEVC.num_short_term_ref_pic_sets", unsafe.Offsetof(pp.NumShortTermRefPicSets), 561},
		{"VAPictureParameterBufferHEVC.num_long_term_ref_pic_sps", unsafe.Offsetof(pp.NumLongTermRefPicSps), 562},
		{"VAPictureParameterBufferHEVC.num_ref_idx_l0_default_active_minus1", unsafe.Offsetof(pp.NumRefIdxL0DefaultActiveMinus1), 563},
		{"VAPictureParameterBufferHEVC.pps_beta_offset_div2", unsafe.Offsetof(pp.PpsBetaOffsetDiv2), 565},
		{"VAPictureParameterBufferHEVC.pps_tc_offset_div2", unsafe.Offsetof(pp.PpsTcOffsetDiv2), 566},
		{"VAPictureParameterBufferHEVC.num_extra_slice_header_bits", unsafe.Offsetof(pp.NumExtraSliceHeaderBits), 567},
		{"VAPictureParameterBufferHEVC.st_rps_bits", unsafe.Offsetof(pp.StRpsBits), 568},
		{"sizeof VASliceParameterBufferHEVC", unsafe.Sizeof(sp), 264},
		{"VASliceParameterBufferHEVC.slice_data_byte_offset", unsafe.Offsetof(sp.SliceDataByteOffset), 12},
		{"VASliceParameterBufferHEVC.slice_segment_address", unsafe.Offsetof(sp.SliceSegmentAddress), 16},
		{"VASliceParameterBufferHEVC.RefPicList", unsafe.Offsetof(sp.RefPicList), 20},
		{"VASliceParameterBufferHEVC.LongSliceFlags", unsafe.Offsetof(sp.LongSliceFlags), 52},
		{"VASliceParameterBufferHEVC.collocated_ref_idx", unsafe.Offsetof(sp.CollocatedRefIdx), 56},
		{"VASliceParameterBufferHEVC.num_ref_idx_l0_active_minus1", unsafe.Offsetof(sp.NumRefIdxL0ActiveMinus1), 57},
		{"VASliceParameterBufferHEVC.slice_qp_delta", unsafe.Offsetof(sp.SliceQpDelta), 59},
		{"VASliceParameterBufferHEVC.slice_cb_qp_offset", unsafe.Offsetof(sp.SliceCbQpOffset), 60},
		{"VASliceParameterBufferHEVC.slice_beta_offset_div2", unsafe.Offsetof(sp.SliceBetaOffsetDiv2), 62},
		{"VASliceParameterBufferHEVC.slice_tc_offset_div2", unsafe.Offsetof(sp.SliceTcOffsetDiv2), 63},
		{"VASliceParameterBufferHEVC.luma_log2_weight_denom", unsafe.Offsetof(sp.LumaLog2WeightDenom), 64},
		{"VASliceParameterBufferHEVC.delta_chroma_log2_weight_denom", unsafe.Offsetof(sp.DeltaChromaLog2WeightDenom), 65},
		{"VASliceParameterBufferHEVC.delta_luma_weight_l0", unsafe.Offsetof(sp.DeltaLumaWeightL0), 66},
		{"VASliceParameterBufferHEVC.luma_offset_l0", unsafe.Offsetof(sp.LumaOffsetL0), 81},
		{"VASliceParameterBufferHEVC.delta_chroma_weight_l0", unsafe.Offsetof(sp.DeltaChromaWeightL0), 96},
		{"VASliceParameterBufferHEVC.ChromaOffsetL0", unsafe.Offsetof(sp.ChromaOffsetL0), 126},
		{"VASliceParameterBufferHEVC.delta_luma_weight_l1", unsafe.Offsetof(sp.DeltaLumaWeightL1), 156},
		{"VASliceParameterBufferHEVC.luma_offset_l1", unsafe.Offsetof(sp.LumaOffsetL1), 171},
		{"VASliceParameterBufferHEVC.delta_chroma_weight_l1", unsafe.Offsetof(sp.DeltaChromaWeightL1), 186},
		{"VASliceParameterBufferHEVC.ChromaOffsetL1", unsafe.Offsetof(sp.ChromaOffsetL1), 216},
		{"VASliceParameterBufferHEVC.five_minus_max_num_merge_cand", unsafe.Offsetof(sp.FiveMinusMaxNumMergeCand), 246},
		{"VASliceParameterBufferHEVC.num_entry_point_offsets", unsafe.Offsetof(sp.NumEntryPointOffsets), 248},
		{"VASliceParameterBufferHEVC.entry_offset_to_subset_array", unsafe.Offsetof(sp.EntryOffsetToSubsetArray), 250},
		{"VASliceParameterBufferHEVC.slice_data_num_emu_prevn_bytes", unsafe.Offsetof(sp.SliceDataNumEmuPrevnBytes), 252},
		{"sizeof VAIQMatrixBufferHEVC", unsafe.Sizeof(iq), 1016},
		{"VAIQMatrixBufferHEVC.ScalingList8x8", unsafe.Offsetof(iq.ScalingList8x8), 96},
		{"VAIQMatrixBufferHEVC.ScalingList16x16", unsafe.Offsetof(iq.ScalingList16x16), 480},
		{"VAIQMatrixBufferHEVC.ScalingList32x32", unsafe.Offsetof(iq.ScalingList32x32), 864},
		{"VAIQMatrixBufferHEVC.ScalingListDC16x16", unsafe.Offsetof(iq.ScalingListDC16x16), 992},
		{"VAIQMatrixBufferHEVC.ScalingListDC32x32", unsafe.Offsetof(iq.ScalingListDC32x32), 998},
		{"sizeof VAEncSequenceParameterBufferHEVC", unsafe.Sizeof(es), 116},
		{"VAEncSequenceParameterBufferHEVC.general_level_idc", unsafe.Offsetof(es.GeneralLevelIDC), 1},
		{"VAEncSequenceParameterBufferHEVC.general_tier_flag", unsafe.Offsetof(es.GeneralTierFlag), 2},
		{"VAEncSequenceParameterBufferHEVC.intra_period", unsafe.Offsetof(es.IntraPeriod), 4},
		{"VAEncSequenceParameterBufferHEVC.intra_idr_period", unsafe.Offsetof(es.IntraIDRPeriod), 8},
		{"VAEncSequenceParameterBufferHEVC.ip_period", unsafe.Offsetof(es.IPPeriod), 12},
		{"VAEncSequenceParameterBufferHEVC.bits_per_second", unsafe.Offsetof(es.BitsPerSecond), 16},
		{"VAEncSequenceParameterBufferHEVC.pic_width_in_luma_samples", unsafe.Offsetof(es.PicWidthInLumaSamples), 20},
		{"VAEncSequenceParameterBufferHEVC.pic_height_in_luma_samples", unsafe.Offsetof(es.PicHeightInLumaSamples), 22},
		{"VAEncSequenceParameterBufferHEVC.seq_fields", unsafe.Offsetof(es.SeqFields), 24},
		{"VAEncSequenceParameterBufferHEVC.log2_min_luma_coding_block_size_minus3", unsafe.Offsetof(es.Log2MinLumaCodingBlockSizeMinus3), 28},
		{"VAEncSequenceParameterBufferHEVC.log2_diff_max_min_luma_coding_block_size", unsafe.Offsetof(es.Log2DiffMaxMinLumaCodingBlockSize), 29},
		{"VAEncSequenceParameterBufferHEVC.log2_min_transform_block_size_minus2", unsafe.Offsetof(es.Log2MinTransformBlockSizeMinus2), 30},
		{"VAEncSequenceParameterBufferHEVC.log2_diff_max_min_transform_block_size", unsafe.Offsetof(es.Log2DiffMaxMinTransformBlockSize), 31},
		{"VAEncSequenceParameterBufferHEVC.max_transform_hierarchy_depth_inter", unsafe.Offsetof(es.MaxTransformHierarchyDepthInter), 32},
		{"VAEncSequenceParameterBufferHEVC.max_transform_hierarchy_depth_intra", unsafe.Offsetof(es.MaxTransformHierarchyDepthIntra), 33},
		{"VAEncSequenceParameterBufferHEVC.pcm_sample_bit_depth_luma_minus1", unsafe.Offsetof(es.PcmSampleBitDepthLumaMinus1), 36},
		{"VAEncSequenceParameterBufferHEVC.pcm_sample_bit_depth_chroma_minus1", unsafe.Offsetof(es.PcmSampleBitDepthChromaMinus1), 40},
		{"VAEncSequenceParameterBufferHEVC.log2_min_pcm_luma_coding_block_size_minus3", unsafe.Offsetof(es.Log2MinPcmLumaCodingBlockSizeMinus3), 44},
		{"VAEncSequenceParameterBufferHEVC.log2_max_pcm_luma_coding_block_size_minus3", unsafe.Offsetof(es.Log2MaxPcmLumaCodingBlockSizeMinus3), 48},
		{"VAEncSequenceParameterBufferHEVC.vui_parameters_present_flag", unsafe.Offsetof(es.VUIParametersPresentFlag), 52},
		{"VAEncSequenceParameterBufferHEVC.vui_fields", unsafe.Offsetof(es.VUIFields), 56},
		{"VAEncSequenceParameterBufferHEVC.aspect_ratio_idc", unsafe.Offsetof(es.AspectRatioIDC), 60},
		{"VAEncSequenceParameterBufferHEVC.sar_width", unsafe.Offsetof(es.SarWidth), 64},
		{"VAEncSequenceParameterBufferHEVC.sar_height", unsafe.Offsetof(es.SarHeight), 68},
		{"VAEncSequenceParameterBufferHEVC.vui_num_units_in_tick", unsafe.Offsetof(es.VUINumUnitsInTick), 72},
		{"VAEncSequenceParameterBufferHEVC.vui_time_scale", unsafe.Offsetof(es.VUITimeScale), 76},
		{"VAEncSequenceParameterBufferHEVC.min_spatial_segmentation_idc", unsafe.Offsetof(es.MinSpatialSegmentationIDC), 80},
		{"VAEncSequenceParameterBufferHEVC.max_bytes_per_pic_denom", unsafe.Offsetof(es.MaxBytesPerPicDenom), 82},
		{"VAEncSequenceParameterBufferHEVC.max_bits_per_min_cu_denom", unsafe.Offsetof(es.MaxBitsPerMinCuDenom), 83},
		{"VAEncSequenceParameterBufferHEVC.scc_fields", unsafe.Offsetof(es.SccFields), 84},
		{"sizeof VAEncPictureParameterBufferHEVC", unsafe.Sizeof(ep), 576},
		{"VAEncPictureParameterBufferHEVC.reference_frames", unsafe.Offsetof(ep.ReferenceFrames), 28},
		{"VAEncPictureParameterBufferHEVC.coded_buf", unsafe.Offsetof(ep.CodedBuf), 448},
		{"VAEncPictureParameterBufferHEVC.collocated_ref_pic_index", unsafe.Offsetof(ep.CollocatedRefPicIndex), 452},
		{"VAEncPictureParameterBufferHEVC.last_picture", unsafe.Offsetof(ep.LastPicture), 453},
		{"VAEncPictureParameterBufferHEVC.pic_init_qp", unsafe.Offsetof(ep.PicInitQp), 454},
		{"VAEncPictureParameterBufferHEVC.diff_cu_qp_delta_depth", unsafe.Offsetof(ep.DiffCuQpDeltaDepth), 455},
		{"VAEncPictureParameterBufferHEVC.pps_cb_qp_offset", unsafe.Offsetof(ep.PpsCbQpOffset), 456},
		{"VAEncPictureParameterBufferHEVC.pps_cr_qp_offset", unsafe.Offsetof(ep.PpsCrQpOffset), 457},
		{"VAEncPictureParameterBufferHEVC.num_tile_columns_minus1", unsafe.Offsetof(ep.NumTileColumnsMinus1), 458},
		{"VAEncPictureParameterBufferHEVC.num_tile_rows_minus1", unsafe.Offsetof(ep.NumTileRowsMinus1), 459},
		{"VAEncPictureParameterBufferHEVC.column_width_minus1", unsafe.Offsetof(ep.ColumnWidthMinus1), 460},
		{"VAEncPictureParameterBufferHEVC.row_height_minus1", unsafe.Offsetof(ep.RowHeightMinus1), 479},
		{"VAEncPictureParameterBufferHEVC.log2_parallel_merge_level_minus2", unsafe.Offsetof(ep.Log2ParallelMergeLevelMinus2), 500},
		{"VAEncPictureParameterBufferHEVC.ctu_max_bitsize_allowed", unsafe.Offsetof(ep.CtuMaxBitsizeAllowed), 501},
		{"VAEncPictureParameterBufferHEVC.num_ref_idx_l0_default_active_minus1", unsafe.Offsetof(ep.NumRefIdxL0DefaultActiveMinus1), 502},
		{"VAEncPictureParameterBufferHEVC.num_ref_idx_l1_default_active_minus1", unsafe.Offsetof(ep.NumRefIdxL1DefaultActiveMinus1), 503},
		{"VAEncPictureParameterBufferHEVC.slice_pic_parameter_set_id", unsafe.Offsetof(ep.SlicePicParameterSetID), 504},
		{"VAEncPictureParameterBufferHEVC.nal_unit_type", unsafe.Offsetof(ep.NalUnitType), 505},
		{"VAEncPictureParameterBufferHEVC.pic_fields", unsafe.Offsetof(ep.PicFields), 508},
		{"VAEncPictureParameterBufferHEVC.hierarchical_level_plus1", unsafe.Offsetof(ep.HierarchicalLevelPlus1), 512},
		{"VAEncPictureParameterBufferHEVC.scc_fields", unsafe.Offsetof(ep.SccFields), 514},
		{"sizeof VAEncSliceParameterBufferHEVC", unsafe.Sizeof(el), 1076},
		{"VAEncSliceParameterBufferHEVC.num_ctu_in_slice", unsafe.Offsetof(el.NumCtuInSlice), 4},
		{"VAEncSliceParameterBufferHEVC.slice_type", unsafe.Offsetof(el.SliceType), 8},
		{"VAEncSliceParameterBufferHEVC.slice_pic_parameter_set_id", unsafe.Offsetof(el.SlicePicParameterSetID), 9},
		{"VAEncSliceParameterBufferHEVC.num_ref_idx_l0_active_minus1", unsafe.Offsetof(el.NumRefIdxL0ActiveMinus1), 10},
		{"VAEncSliceParameterBufferHEVC.num_ref_idx_l1_active_minus1", unsafe.Offsetof(el.NumRefIdxL1ActiveMinus1), 11},
		{"VAEncSliceParameterBufferHEVC.ref_pic_list0", unsafe.Offsetof(el.RefPicList0), 12},
		{"VAEncSliceParameterBufferHEVC.ref_pic_list1", unsafe.Offsetof(el.RefPicList1), 432},
		{"VAEncSliceParameterBufferHEVC.luma_log2_weight_denom", unsafe.Offsetof(el.LumaLog2WeightDenom), 852},
		{"VAEncSliceParameterBufferHEVC.delta_chroma_log2_weight_denom", unsafe.Offsetof(el.DeltaChromaLog2WeightDenom), 853},
		{"VAEncSliceParameterBufferHEVC.delta_luma_weight_l0", unsafe.Offsetof(el.DeltaLumaWeightL0), 854},
		{"VAEncSliceParameterBufferHEVC.luma_offset_l0", unsafe.Offsetof(el.LumaOffsetL0), 869},
		{"VAEncSliceParameterBufferHEVC.delta_chroma_weight_l0", unsafe.Offsetof(el.DeltaChromaWeightL0), 884},
		{"VAEncSliceParameterBufferHEVC.chroma_offset_l0", unsafe.Offsetof(el.ChromaOffsetL0), 914},
		{"VAEncSliceParameterBufferHEVC.delta_luma_weight_l1", unsafe.Offsetof(el.DeltaLumaWeightL1), 944},
		{"VAEncSliceParameterBufferHEVC.luma_offset_l1", unsafe.Offsetof(el.LumaOffsetL1), 959},
		{"VAEncSliceParameterBufferHEVC.delta_chroma_weight_l1", unsafe.Offsetof(el.DeltaChromaWeightL1), 974},
		{"VAEncSliceParameterBufferHEVC.chroma_offset_l1", unsafe.Offsetof(el.ChromaOffsetL1), 1004},
		{"VAEncSliceParameterBufferHEVC.max_num_merge_cand", unsafe.Offsetof(el.MaxNumMergeCand), 1034},
		{"VAEncSliceParameterBufferHEVC.slice_qp_delta", unsafe.Offsetof(el.SliceQpDelta), 1035},
		{"VAEncSliceParameterBufferHEVC.slice_cb_qp_offset", unsafe.Offsetof(el.SliceCbQpOffset), 1036},
		{"VAEncSliceParameterBufferHEVC.slice_cr_qp_offset", unsafe.Offsetof(el.SliceCrQpOffset), 1037},
		{"VAEncSliceParameterBufferHEVC.slice_beta_offset_div2", unsafe.Offsetof(el.SliceBetaOffsetDiv2), 1038},
		{"VAEncSliceParameterBufferHEVC.slice_tc_offset_div2", unsafe.Offsetof(el.SliceTcOffsetDiv2), 1039},
		{"VAEncSliceParameterBufferHEVC.slice_fields", unsafe.Offsetof(el.SliceFields), 1040},
		{"VAEncSliceParameterBufferHEVC.pred_weight_table_bit_offset", unsafe.Offsetof(el.PredWeightTableBitOffset), 1044},
		{"VAEncSliceParameterBufferHEVC.pred_weight_table_bit_length", unsafe.Offsetof(el.PredWeightTableBitLength), 1048},
	}
	for _, c := range checks {
		if c.got != c.want {
			t.Errorf("%s: got %d want %d", c.name, c.got, c.want)
		}
	}
}

// Bit-field positions measured the same way: every field set to all ones
// in turn and the union read back as an integer.
func TestHEVCBitFields(t *testing.T) {
	checks := []struct {
		name string
		got  uint32
		want uint32
	}{
		{"VAPictureParameterBufferHEVC.pic_fields.chroma_format_idc", uint32(3) << HEVCPicChromaFormatIDCShift, 0x3},
		{"VAPictureParameterBufferHEVC.pic_fields.separate_colour_plane_flag", uint32(HEVCPicSeparateColourPlaneFlag), 0x4},
		{"VAPictureParameterBufferHEVC.pic_fields.pcm_enabled_flag", uint32(HEVCPicPcmEnabledFlag), 0x8},
		{"VAPictureParameterBufferHEVC.pic_fields.scaling_list_enabled_flag", uint32(HEVCPicScalingListEnabledFlag), 0x10},
		{"VAPictureParameterBufferHEVC.pic_fields.transform_skip_enabled_flag", uint32(HEVCPicTransformSkipEnabledFlag), 0x20},
		{"VAPictureParameterBufferHEVC.pic_fields.amp_enabled_flag", uint32(HEVCPicAmpEnabledFlag), 0x40},
		{"VAPictureParameterBufferHEVC.pic_fields.strong_intra_smoothing_enabled_flag", uint32(HEVCPicStrongIntraSmoothingEnabledFlag), 0x80},
		{"VAPictureParameterBufferHEVC.pic_fields.sign_data_hiding_enabled_flag", uint32(HEVCPicSignDataHidingEnabledFlag), 0x100},
		{"VAPictureParameterBufferHEVC.pic_fields.constrained_intra_pred_flag", uint32(HEVCPicConstrainedIntraPredFlag), 0x200},
		{"VAPictureParameterBufferHEVC.pic_fields.cu_qp_delta_enabled_flag", uint32(HEVCPicCuQpDeltaEnabledFlag), 0x400},
		{"VAPictureParameterBufferHEVC.pic_fields.weighted_pred_flag", uint32(HEVCPicWeightedPredFlag), 0x800},
		{"VAPictureParameterBufferHEVC.pic_fields.weighted_bipred_flag", uint32(HEVCPicWeightedBipredFlag), 0x1000},
		{"VAPictureParameterBufferHEVC.pic_fields.transquant_bypass_enabled_flag", uint32(HEVCPicTransquantBypassEnabledFlag), 0x2000},
		{"VAPictureParameterBufferHEVC.pic_fields.tiles_enabled_flag", uint32(HEVCPicTilesEnabledFlag), 0x4000},
		{"VAPictureParameterBufferHEVC.pic_fields.entropy_coding_sync_enabled_flag", uint32(HEVCPicEntropyCodingSyncEnabledFlag), 0x8000},
		{"VAPictureParameterBufferHEVC.pic_fields.pps_loop_filter_across_slices_enabled_flag", uint32(HEVCPicPpsLoopFilterAcrossSlicesEnabledFlag), 0x10000},
		{"VAPictureParameterBufferHEVC.pic_fields.loop_filter_across_tiles_enabled_flag", uint32(HEVCPicLoopFilterAcrossTilesEnabledFlag), 0x20000},
		{"VAPictureParameterBufferHEVC.pic_fields.pcm_loop_filter_disabled_flag", uint32(HEVCPicPcmLoopFilterDisabledFlag), 0x40000},
		{"VAPictureParameterBufferHEVC.pic_fields.NoPicReorderingFlag", uint32(HEVCPicNoPicReorderingFlag), 0x80000},
		{"VAPictureParameterBufferHEVC.pic_fields.NoBiPredFlag", uint32(HEVCPicNoBiPredFlag), 0x100000},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.lists_modification_present_flag", uint32(HEVCSliceParsingListsModificationPresentFlag), 0x1},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.long_term_ref_pics_present_flag", uint32(HEVCSliceParsingLongTermRefPicsPresentFlag), 0x2},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.sps_temporal_mvp_enabled_flag", uint32(HEVCSliceParsingSpsTemporalMvpEnabledFlag), 0x4},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.cabac_init_present_flag", uint32(HEVCSliceParsingCabacInitPresentFlag), 0x8},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.output_flag_present_flag", uint32(HEVCSliceParsingOutputFlagPresentFlag), 0x10},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.dependent_slice_segments_enabled_flag", uint32(HEVCSliceParsingDependentSliceSegmentsEnabled), 0x20},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.pps_slice_chroma_qp_offsets_present_flag", uint32(HEVCSliceParsingPpsSliceChromaQpOffsetsPresent), 0x40},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.sample_adaptive_offset_enabled_flag", uint32(HEVCSliceParsingSampleAdaptiveOffsetEnabled), 0x80},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.deblocking_filter_override_enabled_flag", uint32(HEVCSliceParsingDeblockingFilterOverrideEnabled), 0x100},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.pps_disable_deblocking_filter_flag", uint32(HEVCSliceParsingPpsDisableDeblockingFilter), 0x200},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.RapPicFlag", uint32(HEVCSliceParsingRapPicFlag), 0x800},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.IdrPicFlag", uint32(HEVCSliceParsingIdrPicFlag), 0x1000},
		{"VAPictureParameterBufferHEVC.slice_parsing_fields.IntraPicFlag", uint32(HEVCSliceParsingIntraPicFlag), 0x2000},
		{"VASliceParameterBufferHEVC.LongSliceFlags.LastSliceOfPic", uint32(HEVCSliceLastSliceOfPic), 0x1},
		{"VASliceParameterBufferHEVC.LongSliceFlags.dependent_slice_segment_flag", uint32(HEVCSliceDependentSliceSegmentFlag), 0x2},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_type", uint32(3) << HEVCSliceSliceTypeShift, 0xc},
		{"VASliceParameterBufferHEVC.LongSliceFlags.color_plane_id", uint32(3) << HEVCSliceColorPlaneIDShift, 0x30},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_sao_luma_flag", uint32(HEVCSliceSaoLumaFlag), 0x40},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_sao_chroma_flag", uint32(HEVCSliceSaoChromaFlag), 0x80},
		{"VASliceParameterBufferHEVC.LongSliceFlags.mvd_l1_zero_flag", uint32(HEVCSliceMvdL1ZeroFlag), 0x100},
		{"VASliceParameterBufferHEVC.LongSliceFlags.cabac_init_flag", uint32(HEVCSliceCabacInitFlag), 0x200},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_temporal_mvp_enabled_flag", uint32(HEVCSliceTemporalMvpEnabledFlag), 0x400},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_deblocking_filter_disabled_flag", uint32(HEVCSliceDeblockingFilterDisabledFlag), 0x800},
		{"VASliceParameterBufferHEVC.LongSliceFlags.collocated_from_l0_flag", uint32(HEVCSliceCollocatedFromL0Flag), 0x1000},
		{"VASliceParameterBufferHEVC.LongSliceFlags.slice_loop_filter_across_slices_enabled_flag", uint32(HEVCSliceLoopFilterAcrossSlicesEnabledFlag), 0x2000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.chroma_format_idc", uint32(3) << HEVCEncSeqChromaFormatIDCShift, 0x3},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.separate_colour_plane_flag", uint32(HEVCEncSeqSeparateColourPlaneFlag), 0x4},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.bit_depth_luma_minus8", uint32(7) << HEVCEncSeqBitDepthLumaMinus8Shift, 0x38},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.bit_depth_chroma_minus8", uint32(7) << HEVCEncSeqBitDepthChromaMinus8Shift, 0x1c0},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.scaling_list_enabled_flag", uint32(HEVCEncSeqScalingListEnabledFlag), 0x200},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.strong_intra_smoothing_enabled_flag", uint32(HEVCEncSeqStrongIntraSmoothingEnabledFlag), 0x400},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.amp_enabled_flag", uint32(HEVCEncSeqAmpEnabledFlag), 0x800},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.sample_adaptive_offset_enabled_flag", uint32(HEVCEncSeqSampleAdaptiveOffsetEnabledFlag), 0x1000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.pcm_enabled_flag", uint32(HEVCEncSeqPcmEnabledFlag), 0x2000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.pcm_loop_filter_disabled_flag", uint32(HEVCEncSeqPcmLoopFilterDisabledFlag), 0x4000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.sps_temporal_mvp_enabled_flag", uint32(HEVCEncSeqSpsTemporalMvpEnabledFlag), 0x8000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.low_delay_seq", uint32(HEVCEncSeqLowDelaySeq), 0x10000},
		{"VAEncSequenceParameterBufferHEVC.seq_fields.hierachical_flag", uint32(HEVCEncSeqHierachicalFlag), 0x20000},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.aspect_ratio_info_present_flag", uint32(HEVCEncVUIAspectRatioInfoPresentFlag), 0x1},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.neutral_chroma_indication_flag", uint32(HEVCEncVUINeutralChromaIndicationFlag), 0x2},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.field_seq_flag", uint32(HEVCEncVUIFieldSeqFlag), 0x4},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.vui_timing_info_present_flag", uint32(HEVCEncVUITimingInfoPresentFlag), 0x8},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.bitstream_restriction_flag", uint32(HEVCEncVUIBitstreamRestrictionFlag), 0x10},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.tiles_fixed_structure_flag", uint32(HEVCEncVUITilesFixedStructureFlag), 0x20},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.motion_vectors_over_pic_boundaries_flag", uint32(HEVCEncVUIMotionVectorsOverPicBoundaries), 0x40},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.restricted_ref_pic_lists_flag", uint32(HEVCEncVUIRestrictedRefPicListsFlag), 0x80},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.log2_max_mv_length_horizontal", uint32(31) << HEVCEncVUILog2MaxMvLengthHorizontalShift, 0x1f00},
		{"VAEncSequenceParameterBufferHEVC.vui_fields.log2_max_mv_length_vertical", uint32(31) << HEVCEncVUILog2MaxMvLengthVerticalShift, 0x3e000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.idr_pic_flag", uint32(HEVCEncPicIdrPicFlag), 0x1},
		{"VAEncPictureParameterBufferHEVC.pic_fields.coding_type", uint32(7) << HEVCEncPicCodingTypeShift, 0xe},
		{"VAEncPictureParameterBufferHEVC.pic_fields.reference_pic_flag", uint32(HEVCEncPicReferencePicFlag), 0x10},
		{"VAEncPictureParameterBufferHEVC.pic_fields.dependent_slice_segments_enabled_flag", uint32(HEVCEncPicDependentSliceSegmentsEnabledFlag), 0x20},
		{"VAEncPictureParameterBufferHEVC.pic_fields.sign_data_hiding_enabled_flag", uint32(HEVCEncPicSignDataHidingEnabledFlag), 0x40},
		{"VAEncPictureParameterBufferHEVC.pic_fields.constrained_intra_pred_flag", uint32(HEVCEncPicConstrainedIntraPredFlag), 0x80},
		{"VAEncPictureParameterBufferHEVC.pic_fields.transform_skip_enabled_flag", uint32(HEVCEncPicTransformSkipEnabledFlag), 0x100},
		{"VAEncPictureParameterBufferHEVC.pic_fields.cu_qp_delta_enabled_flag", uint32(HEVCEncPicCuQpDeltaEnabledFlag), 0x200},
		{"VAEncPictureParameterBufferHEVC.pic_fields.weighted_pred_flag", uint32(HEVCEncPicWeightedPredFlag), 0x400},
		{"VAEncPictureParameterBufferHEVC.pic_fields.weighted_bipred_flag", uint32(HEVCEncPicWeightedBipredFlag), 0x800},
		{"VAEncPictureParameterBufferHEVC.pic_fields.transquant_bypass_enabled_flag", uint32(HEVCEncPicTransquantBypassEnabledFlag), 0x1000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.tiles_enabled_flag", uint32(HEVCEncPicTilesEnabledFlag), 0x2000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.entropy_coding_sync_enabled_flag", uint32(HEVCEncPicEntropyCodingSyncEnabledFlag), 0x4000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.loop_filter_across_tiles_enabled_flag", uint32(HEVCEncPicLoopFilterAcrossTilesEnabledFlag), 0x8000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.pps_loop_filter_across_slices_enabled_flag", uint32(HEVCEncPicPpsLoopFilterAcrossSlicesEnabledFlag), 0x10000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.scaling_list_data_present_flag", uint32(HEVCEncPicScalingListDataPresentFlag), 0x20000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.screen_content_flag", uint32(HEVCEncPicScreenContentFlag), 0x40000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.enable_gpu_weighted_prediction", uint32(HEVCEncPicEnableGpuWeightedPrediction), 0x80000},
		{"VAEncPictureParameterBufferHEVC.pic_fields.no_output_of_prior_pics_flag", uint32(HEVCEncPicNoOutputOfPriorPicsFlag), 0x100000},
		{"VAEncSliceParameterBufferHEVC.slice_fields.last_slice_of_pic_flag", uint32(HEVCEncSliceLastSliceOfPicFlag), 0x1},
		{"VAEncSliceParameterBufferHEVC.slice_fields.dependent_slice_segment_flag", uint32(HEVCEncSliceDependentSliceSegmentFlag), 0x2},
		{"VAEncSliceParameterBufferHEVC.slice_fields.colour_plane_id", uint32(3) << HEVCEncSliceColourPlaneIDShift, 0xc},
		{"VAEncSliceParameterBufferHEVC.slice_fields.slice_temporal_mvp_enabled_flag", uint32(HEVCEncSliceTemporalMvpEnabledFlag), 0x10},
		{"VAEncSliceParameterBufferHEVC.slice_fields.slice_sao_luma_flag", uint32(HEVCEncSliceSaoLumaFlag), 0x20},
		{"VAEncSliceParameterBufferHEVC.slice_fields.slice_sao_chroma_flag", uint32(HEVCEncSliceSaoChromaFlag), 0x40},
		{"VAEncSliceParameterBufferHEVC.slice_fields.num_ref_idx_active_override_flag", uint32(HEVCEncSliceNumRefIdxActiveOverrideFlag), 0x80},
		{"VAEncSliceParameterBufferHEVC.slice_fields.mvd_l1_zero_flag", uint32(HEVCEncSliceMvdL1ZeroFlag), 0x100},
		{"VAEncSliceParameterBufferHEVC.slice_fields.cabac_init_flag", uint32(HEVCEncSliceCabacInitFlag), 0x200},
		{"VAEncSliceParameterBufferHEVC.slice_fields.slice_deblocking_filter_disabled_flag", uint32(3) << HEVCEncSliceDeblockingFilterDisabledFlagShift, 0xc00},
		{"VAEncSliceParameterBufferHEVC.slice_fields.slice_loop_filter_across_slices_enabled_flag", uint32(HEVCEncSliceLoopFilterAcrossSlicesEnabledFlag), 0x1000},
		{"VAEncSliceParameterBufferHEVC.slice_fields.collocated_from_l0_flag", uint32(HEVCEncSliceCollocatedFromL0Flag), 0x2000},
		{"HEVCFeatures.separate_colour_planes", uint32(3) << HEVCFeatureSeparateColourPlanesShift, 0x3},
		{"HEVCFeatures.scaling_lists", uint32(3) << HEVCFeatureScalingListsShift, 0xc},
		{"HEVCFeatures.amp", uint32(3) << HEVCFeatureAmpShift, 0x30},
		{"HEVCFeatures.sao", uint32(3) << HEVCFeatureSaoShift, 0xc0},
		{"HEVCFeatures.pcm", uint32(3) << HEVCFeaturePcmShift, 0x300},
		{"HEVCFeatures.temporal_mvp", uint32(3) << HEVCFeatureTemporalMvpShift, 0xc00},
		{"HEVCFeatures.strong_intra_smoothing", uint32(3) << HEVCFeatureStrongIntraSmoothingShift, 0x3000},
		{"HEVCFeatures.dependent_slices", uint32(3) << HEVCFeatureDependentSlicesShift, 0xc000},
		{"HEVCFeatures.sign_data_hiding", uint32(3) << HEVCFeatureSignDataHidingShift, 0x30000},
		{"HEVCFeatures.constrained_intra_pred", uint32(3) << HEVCFeatureConstrainedIntraPredShift, 0xc0000},
		{"HEVCFeatures.transform_skip", uint32(3) << HEVCFeatureTransformSkipShift, 0x300000},
		{"HEVCFeatures.cu_qp_delta", uint32(3) << HEVCFeatureCuQpDeltaShift, 0xc00000},
		{"HEVCFeatures.weighted_prediction", uint32(3) << HEVCFeatureWeightedPredictionShift, 0x3000000},
		{"HEVCFeatures.transquant_bypass", uint32(3) << HEVCFeatureTransquantBypassShift, 0xc000000},
		{"HEVCFeatures.deblocking_filter_disable", uint32(3) << HEVCFeatureDeblockingFilterDisableShift, 0x30000000},
		{"HEVCBlockSizes.log2_max_coding_tree_block_size_minus3", uint32(3) << HEVCBlockLog2MaxCodingTreeBlockSizeMinus3Shift, 0x3},
		{"HEVCBlockSizes.log2_min_coding_tree_block_size_minus3", uint32(3) << HEVCBlockLog2MinCodingTreeBlockSizeMinus3Shift, 0xc},
		{"HEVCBlockSizes.log2_min_luma_coding_block_size_minus3", uint32(3) << HEVCBlockLog2MinLumaCodingBlockSizeMinus3Shift, 0x30},
		{"HEVCBlockSizes.log2_max_luma_transform_block_size_minus2", uint32(3) << HEVCBlockLog2MaxLumaTransformBlockSizeMinus2Shift, 0xc0},
		{"HEVCBlockSizes.log2_min_luma_transform_block_size_minus2", uint32(3) << HEVCBlockLog2MinLumaTransformBlockSizeMinus2Shift, 0x300},
		{"HEVCBlockSizes.max_max_transform_hierarchy_depth_inter", uint32(3) << HEVCBlockMaxMaxTransformHierarchyDepthInterShift, 0xc00},
		{"HEVCBlockSizes.min_max_transform_hierarchy_depth_inter", uint32(3) << HEVCBlockMinMaxTransformHierarchyDepthInterShift, 0x3000},
		{"HEVCBlockSizes.max_max_transform_hierarchy_depth_intra", uint32(3) << HEVCBlockMaxMaxTransformHierarchyDepthIntraShift, 0xc000},
		{"HEVCBlockSizes.min_max_transform_hierarchy_depth_intra", uint32(3) << HEVCBlockMinMaxTransformHierarchyDepthIntraShift, 0x30000},
	}
	for _, c := range checks {
		if c.got != c.want {
			t.Errorf("%s: got %#x want %#x", c.name, c.got, c.want)
		}
	}
}
